# Generated by Django 2.2.7 on 2019-11-11 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('auteur', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('designation', models.CharField(max_length=100)),
                ('matiere_technique', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('sujet', models.TextField()),
                ('joueurs', models.ManyToManyField(blank=True, related_name='images', to='blog.Joueur')),
                ('questions', models.ManyToManyField(blank=True, related_name='images', to='blog.Question')),
            ],
        ),
    ]
