# Generated by Django 2.2.7 on 2019-11-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Concerner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('cleImage', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('auteur', models.CharField(max_length=100)),
                ('date_creation', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('matiere_technique', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('sujet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('cleJoueur', models.IntegerField(primary_key=True, serialize=False)),
                ('nomJoueur', models.CharField(max_length=50, null=True)),
                ('motDePasse', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('cleReponse', models.IntegerField(primary_key=True, serialize=False)),
                ('descriptionReponse', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='text1',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('cleTag', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=200)),
                ('image', models.ManyToManyField(through='blog.Contenir', to='blog.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('cleQuestion', models.IntegerField(primary_key=True, serialize=False)),
                ('descriptionQuestion', models.CharField(max_length=200)),
                ('typeQuestion', models.CharField(max_length=200)),
                ('reponses', models.ManyToManyField(through='blog.Associer', to='blog.Reponse')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='questions',
            field=models.ManyToManyField(through='blog.Concerner', to='blog.Question'),
        ),
        migrations.AddField(
            model_name='contenir',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image'),
        ),
        migrations.AddField(
            model_name='contenir',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='concerner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image'),
        ),
        migrations.AddField(
            model_name='concerner',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('cleAvis', models.IntegerField(primary_key=True, serialize=False)),
                ('aime', models.BooleanField(default=False)),
                ('commentaire', models.CharField(max_length=500, null=True)),
                ('cleImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image')),
                ('cleJoueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Joueur')),
            ],
        ),
        migrations.AddField(
            model_name='associer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
        migrations.AddField(
            model_name='associer',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Reponse'),
        ),
    ]
