# Generated by Django 2.2.7 on 2019-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image_joueur_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('cleReponse', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='question',
            name='reponses',
            field=models.ManyToManyField(to='blog.Reponse'),
        ),
    ]
