# Generated by Django 2.2.7 on 2019-11-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191113_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='motDePasse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joueur',
            name='nomJoueur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('cleAvis', models.IntegerField(primary_key=True, serialize=False)),
                ('aime', models.BooleanField()),
                ('commentaire', models.CharField(max_length=500, null=True)),
                ('cleImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image')),
                ('cleJoueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Joueur')),
            ],
        ),
    ]
