# Generated by Django 2.2.7 on 2019-11-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191121_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name2',
            new_name='lsd',
        ),
    ]
