# Generated by Django 2.2.7 on 2019-11-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191121_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lsd',
        ),
    ]
