# Generated by Django 2.2.7 on 2019-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lsd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
