# Generated by Django 2.2.7 on 2019-11-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191121_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('cleJoueur', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomJoueur', models.CharField(max_length=50, null=True)),
                ('motDePasse', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
