# Generated by Django 2.2.7 on 2019-11-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_joueur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joueur',
        ),
    ]
