# Generated by Django 2.2.7 on 2019-11-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_joueur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('cleReponse', models.IntegerField(primary_key=True, serialize=False)),
                ('descriptionReponse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('cleQuestion', models.IntegerField(primary_key=True, serialize=False)),
                ('descriptionQuestion', models.CharField(max_length=200)),
                ('reponses', models.ManyToManyField(through='blog.Associer', to='blog.Reponse')),
            ],
        ),
        migrations.AddField(
            model_name='associer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
        migrations.AddField(
            model_name='associer',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Reponse'),
        ),
    ]
