# Generated by Django 2.2.7 on 2019-11-21 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191121_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('cleJoueur', models.IntegerField(primary_key=True, serialize=False)),
                ('nomJoueur', models.CharField(max_length=50, null=True)),
                ('motDePasse', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('cleImage', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('auteur', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('designation', models.CharField(max_length=100)),
                ('matiere_technique', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('sujet', models.TextField()),
                ('questions', models.ManyToManyField(through='blog.Concerner', to='blog.Question')),
            ],
        ),
        migrations.AddField(
            model_name='concerner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image'),
        ),
        migrations.AddField(
            model_name='concerner',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('cleAvis', models.IntegerField(primary_key=True, serialize=False)),
                ('aime', models.BooleanField(default=False)),
                ('commentaire', models.CharField(max_length=500, null=True)),
                ('cleImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image')),
                ('cleJoueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Joueur')),
            ],
        ),
    ]
