# Generated by Django 2.2.7 on 2019-11-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191121_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_creation',
            field=models.CharField(max_length=20),
        ),
    ]
