# Generated by Django 2.2.7 on 2019-12-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191128_2052'),
        ('blog', '0017_auto_20191128_1246'),
    ]

    operations = [
    ]
