# Generated by Django 2.2.7 on 2019-12-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_merge_20191205_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Concerner',
        ),
    ]
