# Generated by Django 2.2.8 on 2020-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200126_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='associer',
            name='tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
