# Generated by Django 2.2.8 on 2020-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_associer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='associer',
            name='no_tag',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='associer',
            name='tag',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
