# Generated by Django 2.2.9 on 2020-02-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200212_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lien_musba',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
