# Generated by Django 2.2.9 on 2020-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200212_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='designation',
        ),
        migrations.AlterField(
            model_name='image',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
