# Generated by Django 2.2.8 on 2020-02-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200214_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='typeQuestion',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
