# Generated by Django 2.2.8 on 2020-03-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_question_inclu'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prority',
            field=models.IntegerField(default=0),
        ),
    ]
