# Generated by Django 2.2.8 on 2020-03-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_question_prority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='prority',
            new_name='priority',
        ),
    ]
